name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'CI' ]
    types:
      - completed
permissions: { }
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
      - uses: dorny/test-reporter@9098107e2aa7ed7d1150f776ddea55f55c80016b # v1
        name: Upload dotnet test results summary
        with:
          artifact: /dotnet-(.*)-tests-on-(.*)/
          name: 'dotnet-$1-tests-on-$2'
          path: '*.trx'
          reporter: dotnet-trx
